version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:your_key_here
        depends_on:
            - db

    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: tododb
            #MYSQL_USER: root
            #MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
